### ISSUE TITLE
Update to LwIP v2.1

### ISSUE THREAD

**Issue by stevstrong** [stm32duino/LwIP#3]
As the title says, is there any support planned for the latest v2.1 of LwIP?
I am planning to use the STM32duino Ethernet library with the new v2.1 and I am not sure whether that would work without any issue.

**Comment by fpistm** [comment]
Hi @stevstrong 
I have to check if Cube have planned to move on this version and when. --> Found internal request about this. Wait feedback.
Note that the 2.1 as only 7 weeks old and there is also a 2.1.1 of 4 days old which have some bugfixes

Anyway, if someone try to move on this version any PR is welcome ;)

**Comment by fpistm** [comment]
Hi @stevstrong 
It will be updated soon internally to 2.1.1 then I could update this library.

**Comment by stevstrong** [comment]
Thanks, nice to hear about that.
Looking forward to test it.
