### ISSUE TITLE
Ethernet does not work if uC starts with the cable disconnected

### ISSUE THREAD

**Issue by rtek1000** [stm32duino/LwIP#4]
Hello, i would like to report a problem, i got around, but it may be necessary to find another better alternative.

https://community.st.com/s/question/0D50X0000CDolzDSQR/ethernet-does-not-work-if-uc-starts-with-the-cable-disconnected

**Comment by fpistm** [comment]
Hi @rtek1000 
thnaks.
I close this one as it is a duplicate of this one:
https://github.com/stm32duino/STM32Ethernet/issues/42
