### ISSUE TITLE
LwIP 2.1.3 released. What's involved in updating stm32duino/LwIP to use that?

### ISSUE THREAD

**Issue by chrisco484** [stm32duino/LwIP#6]
I just noticed that 2.1.2 was released in 2019 but a new 2.1.3 release was made in November 2021.

Do the 2.1.3 changes affect stm32duino?

Are there plans to support 2.1.3 in this library? 

What would be involved in supporting 2.1.3

**Comment by fpistm** [comment]
Hi @chrisco484 
In fact this library is based on the LwIP modified by ST.
Currently no new released has been done:
https://github.com/STMicroelectronics/stm32_mw_lwip/tags
When done this library could be updated anyway I don't know when nor if it will be updated.
